const builderDataElement =  {
    id: '_' + Math.random().toString(36).substr(2, 9),
    name: "Page 1",
    active: "false",
    state: "builder",
    component: {
      type: null,
      data: null
    },
    properties: {

    },
    code: {
        isMinified: false,
        allowVirtualProperties: false,
        innerText: true,
        lwc: "",
        lightning: ""
    }
}
const ComponentList = [
"Alert"
,"Button Groups"
,"Button Icons"
,"Buttons"
,"Checkbox"
,"Checkbox Button"
,"Checkbox Button Group"
,"Combobox"
,"Data Tables"
// ,"Datepickers"
,"Icons"
,"Input"
,"Modals"
// ,"Notifications"
// ,"Panels"
// ,"Pills"
,"Radio Button Group"
,"Radio Group"
,"Select"
// ,"Tabs"
,"Textarea"
// ,"Toast"
// ,"Tooltips"
];

const gridData  = {
    activeEditor: "lg",
    activeRow: 0,
    activeColumn: 0,
    gridProperties: {
      columnHeight: {
        "lable": "Column Height",
        "value": "100px"
      },
      columnBackgroundColor: {
        "lable": "Background Color",
        "value": "100px"
      }
    },
    properties: {
      gutters: "slds-gutters_medium",
      margin: {
        top: "",
        bottom: ""
      },
      padding: {
        top: "",
        bottom: ""
      },
      data: {
        sm: [
          {
            spacings: {
              margin: {
                top: "",
                bottom: ""
              },
              padding: {
                top: "",
                bottom: "",
              },
            },
            cols: [
              {
                height: 80,
                size: 6,
                visible: [],
                hide: [],
                active: true,
                spacings: {
                  margin: {
                    top: "",
                    bottom: ""
                  },
                  padding: {
                    top: "",
                    bottom: ""
                  },
                }
              }
            ],
            active: true,
            height: "auto",
            horizontal_align: "",
            vertical_align: "",
            reverse: ""
          }
        ],
        md: [
          {
            spacings: {
              margin: {
                top: "",
                bottom: ""
              },
              padding: {
                top: "",
                bottom: "",
              },
            },
            cols: [
              {
                height: 80,
                size: 6,
                visible: [],
                hide: [],
                active: true,
                spacings: {
                  margin: {
                    top: "",
                    bottom: ""
                  },
                  padding: {
                    top: "",
                    bottom: ""
                  },
                }
              }
            ],
            active: true,
            height: "auto",
            horizontal_align: "",
            vertical_align: "",
            reverse: ""
          }
        ],
        lg: [
          {
            spacings: {
              margin: {
                top: "",
                bottom: ""
              },
              padding: {
                top: "",
                bottom: "",
              },
            },
            cols: [
              {
                height: 80,
                size: 6,
                visible: [],
                hide: [],
                active: true,
                spacings: {
                  margin: {
                    top: "",
                    bottom: ""
                  },
                  padding: {
                    top: "",
                    bottom: ""
                  },
                }
              }
            ],
            active: true,
            height: "auto",
            horizontal_align: "",
            vertical_align: "",
            reverse: ""
          }
        ]
      }
    }
}
const gridRow = {
  spacings: {
    margin: {
      top: "",
      bottom: ""
    },
    padding: {
      top: "",
      bottom: "",
    },
  },
  height: "auto",
  horizontal_align: "",
  vertical_align: "",
  reverse: "",
  cols: [
    {
      height: 80,
      size: 6,
      visible: [],
      hide: [],
      active: false,
      spacings: {
        margin: {
          top: "",
          bottom: "",
          left: "",
          right: ""
        },
        padding: {
          top: "",
          bottom: "",
          left: "",
          right: ""
        },
      }
    }
  ],
  active: false
}

const cardData = {
  spacings: {
    margin: {
      "top": "",
      "bottom": "",
      "left": "",
      "right": ""
    },
    padding: {
      "top": "",
      "bottom": "",
      "left": "",
      "right": ""
    }
  },
  remove: {
    header: false,
    icon: false,
    title: false,
    button: false,
    body: false,
    footer: false
  },
  header: {
    remove: false,
    hidden: [],
    spacings: {
      margin: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      },
      padding: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      }
    },
    alignment: "",
    flip: "",
    icon: {
      remove: false,
      hidden: [],
      name: "custom5",
      size: "",
      flip: "",
      type: "custom",
      description: "Description of the icon",
      spacings: {
        margin: {
          "top": "slds-m-top_xxx-small",
          "bottom": "",
          "left": "",
          "right": ""
        },
        padding: {
          "top": "",
          "bottom": "",
          "left": "",
          "right": ""
        }
      }
    },
    title: {
      remove: false,
      hidden: [],
      text: "Accounts",
      size: "slds-text-title",
      color: "slds-text-color_default",
      align: "slds-text-align_left",
      spacings: {
        margin: {
          "top": "",
          "bottom": "",
          "left": "",
          "right": ""
        },
        padding: {
          "top": "",
          "bottom": "",
          "left": "",
          "right": ""
        }
      }
    },
    button: {
      remove: false,
      streched: "",
      hidden: [],
      text: "Button",
      strong: false,
      isDisabled: false,
      theme: "slds-button_neutral",
      spacings: {
        margin: {
          "top": "",
          "bottom": "",
          "left": "",
          "right": ""
        },
        padding: {
          "top": "",
          "bottom": "",
          "left": "",
          "right": ""
        }
      },
      icon: {
        name: "",
        type: "",
        position: "",
      },
    }
  },
  body: {
    remove: false,
    color: "slds-text-color_default",
    hidden: [],
    text: "Anything can go into the card body",
    align: "slds-text-align_left",
    spacings: {
      margin: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      },
      padding: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      }
    },
    size: ""
  },
  footer: {
    remove: false,
    hidden: [],
    spacings: {
      margin: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      },
      padding: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      }
    },
    align: "slds-text-align_center",
    textAlign: "",
    text: "View All"
  },
  selectedProperties: {
    header:true,
    headerIcon: false,
    headerTitle: false,
    headerButton: false,
    body: false,
    footer: false
  }
}
const textareaData = {
  spacings: {
    margin: {
      "top": "",
      "bottom": "",
      "left": "",
      "right": ""
    },
    padding: {
      "top": "",
      "bottom": "",
      "left": "",
      "right": ""
    }
  },
  hidden: [],
  value: "",
  isDisabled: false,
  isRequired: true,
  isReadonly: false,
  isError: true,
  label: {
    text: "Textarea Label",
    spacings: {
      margin: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      },
      padding: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      }
    },
    hidden: [],
  },
  error: {
    text: "This field is required",
    astreik: {
      float: "left",
      spacings: {
        margin: {
          "top": "",
          "bottom": "",
          "left": "",
          "right": ""
        },
        padding: {
          "top": "",
          "bottom": "",
          "left": "",
          "right": ""
        }
      },
      hidden: [],
    },
    isfloatRight: "slds-float--right",
    spacings: {
      margin: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      },
      padding: {
        "top": "",
        "bottom": "",
        "left": "",
        "right": ""
      }
    },
    hidden: [],
  }
}
const alertData = {
  spacings: {
    margin: {
      "top": "",
      "bottom": "",
      "left": "",
      "right": ""
    },
    padding: {
      "top": "",
      "bottom": "",
      "left": "",
      "right": ""
    }
  },
  hidden: [],
  text: "",
  theme: "",
  icon: {
    name: "",
    type: "",
    hidden: []
  },
  link: {
    href: "",
    text: ""
  },
  close: {
    icon: {
      name: "",
      type: "",
      hidden: []
    }
  }
}
const iconList = [
  {
      "type": "action",
      "icons": [
          "add_contact",
          "add_file",
          "add_photo_video",
          "add_relationship",
          "announcement",
          "apex",
          "approval",
          "back",
          "bug",
          "call",
          "canvas",
          "change_owner",
          "change_record_type",
          "check",
          "clone",
          "close",
          "defer",
          "delete",
          "description",
          "dial_in",
          "download",
          "edit_groups",
          "edit_relationship",
          "edit",
          "email",
          "fallback",
          "filter",
          "flow",
          "follow",
          "following",
          "freeze_user",
          "goal",
          "google_news",
          "info",
          "join_group",
          "lead_convert",
          "leave_group",
          "log_a_call",
          "log_event",
          "manage_perm_sets",
          "map",
          "more",
          "new_account",
          "new_campaign",
          "new_case",
          "new_child_case",
          "new_contact",
          "new_event",
          "new_group",
          "new_lead",
          "new_note",
          "new_notebook",
          "new_opportunity",
          "new_person_account",
          "new_task",
          "new",
          "password_unlock",
          "preview",
          "priority",
          "question_post_action",
          "quote",
          "recall",
          "record",
          "refresh",
          "reject",
          "remove_relationship",
          "remove",
          "reset_password",
          "script",
          "share_file",
          "share_link",
          "share_poll",
          "share_post",
          "share_thanks",
          "share",
          "sort",
          "submit_for_approval",
          "update_status",
          "update",
          "upload",
          "user_activation",
          "user",
          "view_relationship",
          "web_link"
      ]
  },
  {
      "type": "custom",
      "icons": [
          "custom1",
          "custom2",
          "custom3",
          "custom4",
          "custom5",
          "custom6",
          "custom7",
          "custom8",
          "custom9",
          "custom10",
          "custom11",
          "custom12",
          "custom13",
          "custom14",
          "custom15",
          "custom16",
          "custom17",
          "custom18",
          "custom19",
          "custom20",
          "custom21",
          "custom22",
          "custom23",
          "custom24",
          "custom25",
          "custom26",
          "custom27",
          "custom28",
          "custom29",
          "custom30",
          "custom31",
          "custom32",
          "custom33",
          "custom34",
          "custom35",
          "custom36",
          "custom37",
          "custom38",
          "custom39",
          "custom40",
          "custom41",
          "custom42",
          "custom43",
          "custom44",
          "custom45",
          "custom46",
          "custom47",
          "custom48",
          "custom49",
          "custom50",
          "custom51",
          "custom52",
          "custom53",
          "custom54",
          "custom55",
          "custom56",
          "custom57",
          "custom58",
          "custom59",
          "custom60",
          "custom61",
          "custom62",
          "custom63",
          "custom64",
          "custom65",
          "custom66",
          "custom67",
          "custom68",
          "custom69",
          "custom70",
          "custom71",
          "custom72",
          "custom73",
          "custom74",
          "custom75",
          "custom76",
          "custom77",
          "custom78",
          "custom79",
          "custom80",
          "custom81",
          "custom82",
          "custom83",
          "custom84",
          "custom85",
          "custom86",
          "custom87",
          "custom88",
          "custom89",
          "custom90",
          "custom91",
          "custom92",
          "custom93",
          "custom94",
          "custom95",
          "custom96",
          "custom97",
          "custom98",
          "custom99",
          "custom100",
          "custom101",
          "custom102",
          "custom103",
          "custom104",
          "custom105",
          "custom106",
          "custom107",
          "custom108",
          "custom109",
          "custom110",
          "custom111",
          "custom112",
          "custom113"
      ]
  },
  {
      "type": "doctype",
      "icons": [
          "ai",
          "attachment",
          "audio",
          "box_notes",
          "csv",
          "eps",
          "excel",
          "exe",
          "flash",
          "folder",
          "gdoc",
          "gdocs",
          "gform",
          "gpres",
          "gsheet",
          "html",
          "image",
          "keynote",
          "library_folder",
          "link",
          "mp4",
          "overlay",
          "pack",
          "pages",
          "pdf",
          "ppt",
          "psd",
          "quip_doc",
          "quip_sheet",
          "quip_slide",
          "rtf",
          "slide",
          "stypi",
          "txt",
          "unknown",
          "video",
          "visio",
          "webex",
          "word",
          "xml",
          "zip"
      ]
  },
  {
      "type": "standard",
      "icons": [
          "account",
          "action_list_component",
          "actions_and_buttons",
          "address",
          "agent_session",
          "all",
          "announcement",
          "answer_best",
          "answer_private",
          "answer_public",
          "apex_plugin",
          "apex",
          "app",
          "approval",
          "apps_admin",
          "apps",
          "article",
          "asset_relationship",
          "assigned_resource",
          "assignment",
          "avatar_loading",
          "avatar",
          "bot_training",
          "bot",
          "branch_merge",
          "brand",
          "business_hours",
          "buyer_account",
          "buyer_group",
          "calibration",
          "call_history",
          "call",
          "campaign_members",
          "campaign",
          "canvas",
          "carousel",
          "case_change_status",
          "case_comment",
          "case_email",
          "case_log_a_call",
          "case_milestone",
          "case_transcript",
          "case",
          "catalog",
          "category",
          "channel_program_history",
          "channel_program_levels",
          "channel_program_members",
          "channel_programs",
          "chart",
          "choice",
          "client",
          "cms",
          "coaching",
          "code_playground",
          "collection_variable",
          "connected_apps",
          "constant",
          "contact_list",
          "contact_request",
          "contact",
          "contract_line_item",
          "contract",
          "currency_input",
          "currency",
          "custom_notification",
          "custom",
          "customer_360",
          "customer_portal_users",
          "customers",
          "dashboard_ea",
          "dashboard",
          "data_integration_hub",
          "datadotcom",
          "dataset",
          "date_input",
          "date_time",
          "decision",
          "default",
          "delegated_account",
          "display_rich_text",
          "display_text",
          "document",
          "drafts",
          "dynamic_record_choice",
          "education",
          "email_chatter",
          "email",
          "empty",
          "endorsement",
          "entitlement_policy",
          "entitlement_process",
          "entitlement_template",
          "entitlement",
          "entity_milestone",
          "entity",
          "environment_hub",
          "event",
          "events",
          "feed",
          "feedback",
          "file",
          "filter",
          "first_non_empty",
          "flow",
          "folder",
          "forecasts",
          "formula",
          "fulfillment_order",
          "generic_loading",
          "global_constant",
          "goals",
          "group_loading",
          "groups",
          "hierarchy",
          "high_velocity_sales",
          "home",
          "household",
          "individual",
          "insights",
          "instore_locations",
          "investment_account",
          "invocable_action",
          "iot_context",
          "iot_orchestrations",
          "javascript_button",
          "job_profile",
          "kanban",
          "knowledge",
          "lead_insights",
          "lead_list",
          "lead",
          "letterhead",
          "lightning_component",
          "lightning_usage",
          "link",
          "list_email",
          "live_chat_visitor",
          "live_chat",
          "location",
          "log_a_call",
          "logging",
          "loop",
          "macros",
          "maintenance_asset",
          "maintenance_plan",
          "marketing_actions",
          "merge",
          "messaging_conversation",
          "messaging_session",
          "messaging_user",
          "metrics",
          "multi_picklist",
          "multi_select_checkbox",
          "news",
          "note",
          "number_input",
          "omni_supervisor",
          "operating_hours",
          "opportunity_contact_role",
          "opportunity_splits",
          "opportunity",
          "order_item",
          "orders",
          "outcome",
          "output",
          "partner_fund_allocation",
          "partner_fund_claim",
          "partner_fund_request",
          "partner_marketing_budget",
          "partners",
          "password",
          "past_chat",
          "people",
          "performance",
          "person_account",
          "photo",
          "picklist_choice",
          "picklist_type",
          "planogram",
          "poll",
          "portal_roles_and_subordinates",
          "portal_roles",
          "portal",
          "post",
          "pricebook",
          "process",
          "product_consumed",
          "product_item_transaction",
          "product_item",
          "product_request_line_item",
          "product_request",
          "product_required",
          "product_transfer",
          "product",
          "proposition",
          "question_best",
          "question_feed",
          "queue",
          "quick_text",
          "quip_sheet",
          "quip",
          "quotes",
          "radio_button",
          "read_receipts",
          "recent",
          "record_create",
          "record_delete",
          "record_lookup",
          "record_update",
          "record",
          "recycle_bin",
          "related_list",
          "relationship",
          "report",
          "resource_absence",
          "resource_capacity",
          "resource_preference",
          "resource_skill",
          "return_order_line_item",
          "return_order",
          "reward",
          "rtc_presence",
          "sales_cadence_target",
          "sales_cadence",
          "sales_channel",
          "sales_path",
          "sales_value",
          "salesforce_cms",
          "scan_card",
          "screen",
          "search",
          "service_appointment_capacity_usage",
          "service_appointment",
          "service_contract",
          "service_crew_member",
          "service_crew",
          "service_report",
          "service_resource",
          "service_territory_location",
          "service_territory_member",
          "service_territory",
          "settings",
          "shift_type",
          "shift",
          "shipment",
          "skill_entity",
          "skill_requirement",
          "skill",
          "sms",
          "snippet",
          "snippets",
          "sobject_collection",
          "sobject",
          "social",
          "solution",
          "sort",
          "sossession",
          "stage_collection",
          "stage",
          "steps",
          "store_group",
          "store",
          "story",
          "strategy",
          "survey",
          "system_and_global_variable",
          "task",
          "task2",
          "team_member",
          "template",
          "text_template",
          "text",
          "textarea",
          "textbox",
          "thanks_loading",
          "thanks",
          "timesheet_entry",
          "timesheet",
          "timeslot",
          "today",
          "topic",
          "topic2",
          "trailhead",
          "unmatched",
          "user_role",
          "user",
          "variable",
          "visit_templates",
          "visits",
          "visualforce_page",
          "voice_call",
          "waits",
          "work_capacity_limit",
          "work_capacity_usage",
          "work_order_item",
          "work_order",
          "work_queue",
          "work_type_group",
          "work_type"
      ]
  },
  {
      "type": "utility",
      "icons": [
          "activity",
          "ad_set",
          "add",
          "adduser",
          "advanced_function",
          "advertising",
          "agent_session",
          "alert",
          "all",
          "anchor",
          "animal_and_nature",
          "announcement",
          "answer",
          "answered_twice",
          "apex_plugin",
          "apex",
          "approval",
          "apps",
          "archive",
          "arrowdown",
          "arrowup",
          "assignment",
          "attach",
          "automate",
          "away",
          "back",
          "ban",
          "block_visitor",
          "bold",
          "bookmark",
          "breadcrumbs",
          "broadcast",
          "brush",
          "bucket",
          "builder",
          "call",
          "campaign",
          "cancel_file_request",
          "cancel_transfer",
          "capslock",
          "cart",
          "case",
          "cases",
          "center_align_text",
          "change_owner",
          "change_record_type",
          "chart",
          "chat",
          "check",
          "checkin",
          "chevrondown",
          "chevronleft",
          "chevronright",
          "chevronup",
          "choice",
          "classic_interface",
          "clear",
          "clock",
          "close",
          "collapse_all",
          "collection_variable",
          "color_swatch",
          "comments",
          "company",
          "component_customization",
          "connected_apps",
          "constant",
          "contact_request",
          "contract_alt",
          "contract",
          "copy_to_clipboard",
          "copy",
          "crossfilter",
          "currency_input",
          "currency",
          "custom_apps",
          "cut",
          "dash",
          "database",
          "datadotcom",
          "date_input",
          "date_time",
          "dayview",
          "delete",
          "deprecate",
          "description",
          "desktop_and_phone",
          "desktop_console",
          "desktop",
          "dialing",
          "diamond",
          "dislike",
          "display_rich_text",
          "display_text",
          "dock_panel",
          "down",
          "download",
          "drag_and_drop",
          "drag",
          "dynamic_record_choice",
          "edit_form",
          "edit",
          "education",
          "einstein",
          "email_open",
          "email",
          "emoji",
          "end_call",
          "end_chat",
          "end_messaging_session",
          "engage",
          "enter",
          "erect_window",
          "error",
          "event",
          "events",
          "expand_all",
          "expand_alt",
          "expand",
          "fallback",
          "favorite",
          "feed",
          "file",
          "filter",
          "filterList",
          "flow",
          "food_and_drink",
          "formula",
          "forward_up",
          "forward",
          "frozen",
          "fulfillment_order",
          "full_width_view",
          "global_constant",
          "graph",
          "groups",
          "help_center",
          "help",
          "hide_mobile",
          "hide",
          "hierarchy",
          "high_velocity_sales",
          "home",
          "identity",
          "image",
          "in_app_assistant",
          "inbox",
          "incoming_call",
          "info_alt",
          "info",
          "insert_tag_field",
          "insert_template",
          "inspector_panel",
          "internal_share",
          "italic",
          "jump_to_bottom",
          "jump_to_top",
          "justify_text",
          "kanban",
          "keyboard_dismiss",
          "knowledge_base",
          "layers",
          "layout",
          "leave_conference",
          "left_align_text",
          "left",
          "level_down",
          "level_up",
          "light_bulb",
          "lightning_extension",
          "lightning_inspector",
          "like",
          "link",
          "linked",
          "list",
          "listen",
          "live_message",
          "location",
          "lock",
          "locker_service_api_viewer",
          "locker_service_console",
          "log_a_call",
          "logout",
          "loop",
          "lower_flag",
          "macros",
          "magicwand",
          "mark_all_as_read",
          "matrix",
          "merge_field",
          "merge",
          "metrics",
          "minimize_window",
          "missed_call",
          "money",
          "moneybag",
          "monthlyview",
          "move",
          "multi_picklist",
          "multi_select_checkbox",
          "muted",
          "new_direct_message",
          "new_window",
          "new",
          "news",
          "note",
          "notebook",
          "notification",
          "number_input",
          "office365",
          "offline_cached",
          "offline",
          "omni_channel",
          "open_folder",
          "open",
          "opened_folder",
          "outbound_call",
          "outcome",
          "overflow",
          "package_org_beta",
          "package_org",
          "package",
          "page",
          "palette",
          "password",
          "paste",
          "pause",
          "people",
          "phone_landscape",
          "phone_portrait",
          "photo",
          "picklist_choice",
          "picklist_type",
          "picklist",
          "pin",
          "pinned",
          "play",
          "podcast_webinar",
          "pop_in",
          "power",
          "preview",
          "print",
          "priority",
          "privately_shared",
          "process",
          "prompt_edit",
          "prompt",
          "push",
          "puzzle",
          "question_mark",
          "question",
          "questions_and_answers",
          "quick_text",
          "quip",
          "quotation_marks",
          "quote",
          "radio_button",
          "rating",
          "reassign",
          "record_create",
          "record_delete",
          "record_lookup",
          "record_update",
          "record",
          "recurring_exception",
          "recycle_bin_empty",
          "recycle_bin_full",
          "redo",
          "refresh",
          "relate",
          "reminder",
          "remove_formatting",
          "remove_link",
          "replace",
          "reply_all",
          "reply",
          "report_issue",
          "reset_password",
          "resource_absence",
          "resource_capacity",
          "resource_territory",
          "retail_execution",
          "retweet",
          "ribbon",
          "richtextbulletedlist",
          "richtextindent",
          "richtextnumberedlist",
          "richtextoutdent",
          "right_align_text",
          "right",
          "rotate",
          "routing_offline",
          "rows",
          "rules",
          "salesforce1",
          "save",
          "screen",
          "search",
          "send",
          "sentiment_negative",
          "sentiment_neutral",
          "settings",
          "setup_assistant_guide",
          "setup_modal",
          "setup",
          "share_file",
          "share_mobile",
          "share_post",
          "share",
          "shield",
          "shift_ui",
          "shopping_bag",
          "shortcuts",
          "side_list",
          "signpost",
          "skip_back",
          "skip_forward",
          "skip",
          "smiley_and_people",
          "sms",
          "snippet",
          "sobject_collection",
          "sobject",
          "socialshare",
          "sort",
          "spinner",
          "stage_collection",
          "stage",
          "standard_objects",
          "steps",
          "stop",
          "store",
          "strategy",
          "strikethrough",
          "success",
          "summary",
          "summarydetail",
          "survey",
          "switch",
          "symbols",
          "sync",
          "system_and_global_variable",
          "table",
          "tablet_landscape",
          "tablet_portrait",
          "tabset",
          "task",
          "text_background_color",
          "text_color",
          "text_template",
          "text",
          "textarea",
          "textbox",
          "threedots_vertical",
          "threedots",
          "thunder",
          "tile_card_list",
          "toggle_panel_bottom",
          "toggle_panel_left",
          "toggle_panel_right",
          "toggle_panel_top",
          "topic",
          "topic2",
          "touch_action",
          "tracker",
          "trail",
          "trailhead",
          "travel_and_places",
          "trending",
          "turn_off_notifications",
          "type_tool",
          "type",
          "undelete",
          "undeprecate",
          "underline",
          "undo",
          "unlinked",
          "unlock",
          "unmuted",
          "up",
          "upload",
          "user_role",
          "user",
          "variable",
          "video",
          "voicemail_drop",
          "volume_high",
          "volume_low",
          "volume_off",
          "waits",
          "warning",
          "weeklyview",
          "wifi",
          "work_order_type",
          "world",
          "yubi_key",
          "zoomin",
          "zoomout"
      ]
  }
]
const builderData = [ builderDataElement ];
export { builderData, 
  ComponentList, 
  builderDataElement, 
  gridData, 
  gridRow, 
  cardData, 
  textareaData, 
  iconList,
  alertData
};